version: "3.4"
services:
  neko:
    image: "aftorn/neko:chromium"
    restart: "unless-stopped"
    shm_size: "2gb"
    ports:
      - "8080:8080"
      - "8081:8081"
    cap_add:
      - SYS_ADMIN
    environment:
      TZ: Asia/Tokyo
      LANGUAGE: ja-jp
      NEKO_SCREEN: 1280x720@30
      NEKO_PASSWORD: neko
      NEKO_PASSWORD_ADMIN: admin
      NEKO_TCPMUX: 8081
      NEKO_UDPMUX: 8081
      NEKO_ICELITE: 1
      NEKO_FILE_TRANSFER_ENABLED: 1
      NEKO_FILE_TRANSFER_PATH: "/home/neko/Downloads"
      # NEKO_VIDEO_CODEC: h264
  # nekog:
  #   image: "aftorn/neko:nvidia-google-chrome"
  #   restart: "unless-stopped"
  #   shm_size: "2gb"
  #   ports:
  #     - "8080:8080"
  #     - "8081:8081"
  #   cap_add:
  #     - SYS_ADMIN
  #   environment:
  #     TZ: Asia/Tokyo
  #     LANGUAGE: ja-jp
  #     NEKO_SCREEN: 1600x900@60
  #     NEKO_PASSWORD: neko
  #     NEKO_PASSWORD_ADMIN: admin
  #     NEKO_TCPMUX: 8081
  #     NEKO_UDPMUX: 8081
  #     NEKO_ICELITE: 1
  #     NEKO_FILE_TRANSFER_ENABLED: 1
  #     NEKO_FILE_TRANSFER_PATH: "/home/neko/Downloads"
  #     NEKO_VIDEO_CODEC: h264
  #     NEKO_HWENC: nvenc
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1
  #             capabilities: [gpu]

