version: "3.4"
services:
  neko:
    image: "aftorn/neko:chromium"
    restart: "unless-stopped"
    shm_size: "2gb"
    ports:
      - "8080:8080"
      - "8082:8082"
    cap_add:
      - SYS_ADMIN
    environment:
      TZ: Asia/Tokyo
      LANGUAGE: ja-jp
      NEKO_SCREEN: 1280x720@30
      NEKO_PASSWORD: neko
      NEKO_PASSWORD_ADMIN: admin
      NEKO_TCPMUX: 8082
      NEKO_UDPMUX: 8082
      NEKO_ICELITE: 1
      NEKO_FILE_TRANSFER_ENABLED: 1
      NEKO_FILE_TRANSFER_PATH: "/home/neko/Downloads"
